#!/bin/sh

set -e;

TZ=${TZ:-$(cat /etc/TZ)}

if [ "x$TZ" != "x$(cat /etc/TZ)" ]; then
  echo "$TZ" > /etc/TZ

  if [ "x$NAMED_TZ" = "x1" ]; then
    apk add --no-cache --quiet tzdata

    cp /usr/share/zoneinfo/$TZ /etc/localtime
    echo "$TZ" > /etc/timezone
  else
    apk del --no-cache --quiet tzdata
  fi
fi

echo "Timezone : $TZ | date : $(date)
----------------------------------------------------"
